### PR TITLE
Update CI/CD and formatting to latest CFPB practice

### PR DESCRIPTION
**Pull request by willbarton**
This PR:

- Removes Travis in favor of GitHub Actions for running tests
- Adds a GitHub Action to publish to PyPI on release
- Updates the unittest configuration to test against Python 3.6 and 3.8
- Replaces the `flake8` test environment with `lint` that runs Black, flake8, and isort.
- Reformats the code with Black.

This is in line with current CFPB practice for our Python tools and libraries.

### CODE REVIEW

**Comment by Scotchester** [comment]
Why isn't the CI workflow being run?

**Review by higs4281 — COMMENTED** [review]
Should cfpb-python-library-ci.yml be in .github/workflows/ ?

**Comment by willbarton** [comment]
> Should cfpb-python-library-ci.yml be in .github/workflows/ ?

Doh! That'd be it.

**Review by higs4281 — APPROVED** [review]
Looks right, as far as I can test it.

**Pull request merged**
